sudo: required
services:
  - docker

before_install:
  - docker build -t vahid_ce/docker-react -f Dockerfile.dev .


script:
- docker run -e CI=true vahid_ce/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-211125384917"
  bucket_path: "frontend_path"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"